### PR TITLE
New tracks

### PR DESCRIPTION
**Pull request by BenSFGamer**
I've updated the js.list in accordance with the new tracks. But do to the size of the audio files (not really that huge, btw) I wasn't able to upload them. So alternate method would be to link you the files so you could handle it on your end.

### CODE REVIEW

**Comment by Mcdonoughd** [comment]
Sounds good, djpk@jetsetradiofuture.live should work

**Comment by Mcdonoughd** [comment]
I got them, I will put them up after some local testing

**Comment by Mcdonoughd** [comment]
Those files were very large because they were wav. Should be about 12MB maximum as an mp3.

**Comment by BenSFGamer** [comment]
Sounds good. Thanks.

**Pull request merged**
